site_name: Statistical Learning with R
site_url: https://zhipenghe.me/Statistical-Learning-with-R/
nav:
    - Home: index.md
    - Chapter 2: Chapter_2.md
    - About: about.md
theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  